// !!@ Generated File
export let a_effectMetas =  [
{ label: 'bestill', import_path: 'videoKit/effects/aset/eff_bestill.js', ui_label: 'bestill'},
{ label: 'bodypix', import_path: 'videoKit/effects/cset/eff_bodypix.js', ui_label: 'bodypix'},
{ label: 'bright', import_path: 'videoKit/effects/aset/eff_bright.js', ui_label: 'bright'},
{ label: 'circle', import_path: 'videoKit/effects/aset/eff_circle.js', ui_label: 'circle'},
{ label: 'delaunay', import_path: 'videoKit/effects/aset/eff_delaunay.js', ui_label: 'delaunay'},
{ label: 'diff', import_path: 'videoKit/effects/aset/eff_diff.js', ui_label: 'diff'},
{ label: 'face_band', import_path: 'videoKit/effects/fft/eff_face_band.js', ui_label: 'face_band'},
{ label: 'face_mesh', import_path: 'videoKit/effects/bset/eff_face_mesh.js', ui_label: 'face_mesh'},
{ label: 'fft_graph', import_path: 'videoKit/effects/fft/eff_fft_graph.js', ui_label: 'fft_graph'},
{ label: 'fft_polar', import_path: 'videoKit/effects/fft/eff_fft_polar.js', ui_label: 'fft_polar'},
{ label: 'grid', import_path: 'videoKit/effects/aset/eff_grid.js', ui_label: 'grid'},
{ label: 'image', import_path: 'videoKit/effects/cset/eff_image.js', ui_label: 'image'},
{ label: 'image_mesh', import_path: 'videoKit/effects/cset/eff_image_mesh.js', ui_label: 'image_mesh'},
{ label: 'image_url', import_path: 'videoKit/effects/aset/eff_image_url.js', ui_label: 'image_url'},
{ label: 'loop', import_path: 'videoKit/effects/cset/eff_loop.js', ui_label: 'loop'},
{ label: 'maze', import_path: 'videoKit/effects/aset/eff_maze.js', ui_label: 'maze'},
{ label: 'mov', import_path: 'videoKit/effects/cset/eff_mov.js', ui_label: 'mov'},
{ label: 'none', import_path: 'videoKit/effects/bset/eff_none.js', ui_label: 'none'},
{ label: 'phyllotaxis', import_path: 'videoKit/effects/aset/eff_phyllotaxis.js', ui_label: 'phyllotaxis'},
{ label: 'pose_net', import_path: 'videoKit/effects/cset/eff_pose_net.js', ui_label: 'pose_net'},
{ label: 'show', import_path: 'videoKit/effects/bset/eff_show.js', ui_label: 'show'},
{ label: 'sketchy', import_path: 'videoKit/effects/bset/eff_sketchy.js', ui_label: 'sketchy'},
{ label: 'slant_scan', import_path: 'videoKit/effects/bset/eff_slant_scan.js', ui_label: 'slant_scan'},
{ label: 'slit_scan', import_path: 'videoKit/effects/bset/eff_slit_scan.js', ui_label: 'slit_scan'},
{ label: 'ticker', import_path: 'videoKit/effects/ticker/eff_ticker.js', ui_label: 'ticker'},
{ label: 'tile_clock', import_path: 'videoKit/effects/cset/eff_tile_clock.js', ui_label: 'tile_clock'},
{ label: 'tile_live', import_path: 'videoKit/effects/cset/eff_tile_live.js', ui_label: 'tile_live'},
{ label: 'triangle', import_path: 'videoKit/effects/bset/eff_triangle.js', ui_label: 'triangle'},
];
