// !!@ Generated File
export let a_effectMetas =  [
{ label: 'bestill', import_path: 'videoKit/eff/eff_bestill.js' },
{ label: 'bodypix', import_path: 'videoKit/eff/eff_bodypix.js' },
{ label: 'bright', import_path: 'videoKit/eff/eff_bright.js' },
{ label: 'circle', import_path: 'videoKit/eff/eff_circle.js' },
{ label: 'delaunay', import_path: 'videoKit/eff/eff_delaunay.js' },
{ label: 'diff', import_path: 'videoKit/eff/eff_diff.js' },
{ label: 'face_band', import_path: 'videoKit/eff/eff_face_band.js' },
{ label: 'face_mesh', import_path: 'videoKit/eff/eff_face_mesh.js' },
{ label: 'fft_graph', import_path: 'videoKit/eff/eff_fft_graph.js' },
{ label: 'fft_polar', import_path: 'videoKit/eff2/eff_fft_polar.js' },
{ label: 'grid', import_path: 'videoKit/eff2/eff_grid.js' },
{ label: 'image', import_path: 'videoKit/eff2/eff_image.js' },
{ label: 'maze', import_path: 'videoKit/eff2/eff_maze.js' },
{ label: 'mov', import_path: 'videoKit/eff2/eff_mov.js' },
{ label: 'none', import_path: 'videoKit/eff3/eff_none.js' },
{ label: 'pose_net', import_path: 'videoKit/eff3/eff_pose_net.js' },
{ label: 'show', import_path: 'videoKit/eff3/eff_show.js' },
{ label: 'sketchy', import_path: 'videoKit/eff3/eff_sketchy.js' },
{ label: 'slant_scan', import_path: 'videoKit/eff3/eff_slant_scan.js' },
{ label: 'slit_scan', import_path: 'videoKit/eff3/eff_slit_scan.js' },
{ label: 'ticker', import_path: 'videoKit/eff-ticker/eff_ticker.js' },
{ label: 'triangle', import_path: 'videoKit/eff3/eff_triangle.js' },
];
