// EffectRef
// { label, factory, path }

let a_effectRefs = [
  { label: 'show', factory: eff_show_pad },
  { label: 'none', factory: eff_show_none },
  // { label: 'bestill', factory: eff_bestill, import: 'eff/Eff_bestill'},
  { label: 'bestill', import_path: 'eff/eff_bestill' },
  { label: 'bodypix', factory: eff_bodypix },
  { label: 'bright', factory: eff_bright },
  { label: 'circle', factory: eff_circle },
  { label: 'delaunay', factory: eff_delaunay },
  { label: 'diff', factory: eff_diff },
  { label: 'face_band', factory: eff_face_band },
  { label: 'face_mesh', factory: eff_face_mesh },
  { label: 'fft_graph', factory: eff_fft_graph },
  { label: 'fft_polar', factory: eff_fft_polar },
  { label: 'grid', factory: eff_grid },
  { label: 'image_mesh', factory: eff_image_mesh },
  { label: 'image', factory: eff_image_show },
  { label: 'loop', factory: eff_loop },
  { label: 'maze', factory: eff_maze },
  { label: 'mov', factory: eff_mov_show },
  { label: 'pose_net', factory: eff_pose_net },
  { label: 'sketchy', factory: eff_sketchy },
  { label: 'slant_scan', factory: eff_slant_scan },
  { label: 'slit_scan', factory: eff_slit_scan },
  { label: 'text', factory: eff_text },
  { label: 'tile_clock', factory: eff_tile_clock },
  { label: 'tile', factory: eff_tile },
  { label: 'triangle', factory: eff_triangle },
  // { label: 'face_flat', factory: eff_face_flat },
  // { label: 'face_points', factory: eff_face_points },
  // { label: 'line', factory: eff_line },
  // { label: 'mask', factory: eff_mask },
  // { label: 'mirror_x', factory: eff_mirror_x },
  // { label: 'reflect_x', factory: eff_reflect_x },
  // { label: 'scan_co', factory: eff_scan_co },
  // { label: 'scan_polar', factory: eff_scan_polar },
  // { label: 'tunnel', factory: eff_tunnel },
];
