// !!@ Generated File
  let a_effectMetas = [
  { label: 'bestill', import_path: 'eff/eff_bestill' },
{ label: 'bodypix', import_path: 'eff/eff_bodypix' },
{ label: 'bright', import_path: 'eff/eff_bright' },
{ label: 'circle', import_path: 'eff/eff_circle' },
{ label: 'delaunay', import_path: 'eff/eff_delaunay' },
{ label: 'diff', import_path: 'eff/eff_diff' },
{ label: 'face_band', import_path: 'eff/eff_face_band' },
{ label: 'face_mesh', import_path: 'eff/eff_face_mesh' },
{ label: 'fft_graph', import_path: 'eff/eff_fft_graph' },
{ label: 'fft_polar', import_path: 'eff/eff_fft_polar' },
{ label: 'grid', import_path: 'eff/eff_grid' },
{ label: 'image', import_path: 'eff2/eff_image' },
{ label: 'image_mesh', import_path: 'eff2/eff_image_mesh' },
{ label: 'loop', import_path: 'eff2/eff_loop' },
{ label: 'maze', import_path: 'eff2/eff_maze' },
{ label: 'mov', import_path: 'eff2/eff_mov' },
{ label: 'none', import_path: 'eff2/eff_none' },
{ label: 'pose_net', import_path: 'eff2/eff_pose_net' },
{ label: 'show', import_path: 'eff2/eff_show' },
{ label: 'sketchy', import_path: 'eff2/eff_sketchy' },
{ label: 'slant_scan', import_path: 'eff2/eff_slant_scan' },
{ label: 'slit_scan', import_path: 'eff2/eff_slit_scan' },
{ label: 'text', import_path: 'eff2/eff_text' },
{ label: 'tile', import_path: 'eff2/eff_tile' },
{ label: 'tile_clock', import_path: 'eff2/eff_tile_clock' },
{ label: 'triangle', import_path: 'eff2/eff_triangle' },
  ]
  