// !!@ Generated File
let a_settingMetas = [
  { label: '0-club', import_path: 'settings/baked/0-club.json' },
  { label: '0-color-line-1900', import_path: 'settings/baked/0-color-line-1900.json' },
  { label: '0-covid19m', import_path: 'settings/baked/0-covid19m.json' },
  { label: '0-face-live', import_path: 'settings/baked/0-face-live.json' },
  { label: '0-face-tile', import_path: 'settings/baked/0-face-tile.json' },
  { label: '0-facet-hd', import_path: 'settings/baked/0-facet-hd.json' },
  { label: '0-skin-tone-left', import_path: 'settings/baked/0-skin-tone-left.json' },
  { label: '0-skin-tone-right', import_path: 'settings/baked/0-skin-tone-right.json' },
  { label: '0-street-bestill-face-pose', import_path: 'settings/baked/0-street-bestill-face-pose.json' },
  { label: '0-street-big-face', import_path: 'settings/baked/0-street-big-face.json' },
  { label: '0-street-bright-face-pose', import_path: 'settings/baked/0-street-bright-face-pose.json' },
  { label: '0-street-fig-face', import_path: 'settings/baked/0-street-fig-face.json' },
  { label: '0-street-grid-face-pose', import_path: 'settings/baked/0-street-grid-face-pose.json' },
  { label: '0-street-slant-dots', import_path: 'settings/baked/0-street-slant-dots.json' },
  { label: '0-street-slant', import_path: 'settings/baked/0-street-slant.json' },
  { label: '0-street-slit', import_path: 'settings/baked/0-street-slit.json' },
  { label: '1-bestill', import_path: 'settings/baked/1-bestill.json' },
  { label: '9-data-slides', import_path: 'settings/baked/9-data-slides.json' },
];
